name: meditation_theme
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"
homepage: "https://kodingworks.io"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../shared/core
  component:
    path: ../../shared/component
  dependencies:
    path: ../../shared/dependencies
  l10n:
    path: ../../shared/l10n
  preferences:
    path: ../../shared/preferences
  home:
    path: ../home
  settings:
    path: ../settings
  review_app:
    path: ../review_app
  reports:
    path: ../reports
  assets_audio_player: 3.0.5
  audioplayers: 1.0.1
  flutter_downloader:

dev_dependencies:
  flutter_test:
    sdk: flutter
  get_it: 7.2.0
  build_runner: 2.2.0
  hive_generator: 1.1.3
  flutter_lints: 2.0.1

flutter:
