name: review_app
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"
homepage: "https://kodingworks.io"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../shared/core
  component:
    path: ../../shared/component
  dependencies:
    path: ../../shared/dependencies
  l10n:
    path: ../../shared/l10n
  preferences:
    path: ../../shared/preferences
  meditation_theme:
    path: ../meditation_theme
  home:
    path: ../home
  reports:
    path: ../reports

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
