name: dependencies
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"
homepage: "https://kodingworks.io/"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: 0.10.1
  dio: 4.0.6
  equatable: 2.0.3
  flutter_bloc: 8.1.1
  formz: 0.4.1
  get_it: 7.2.0
  image_picker: 0.8.5+3
  path_provider: 2.0.11
  intl: 0.17.0
  carousel_slider: 4.1.1
  rxdart: 0.27.5
  url_launcher: 6.1.5
  package_info: 2.0.2
  shared_preferences: 2.0.15

  flutter_svg: 1.1.3
  dotted_border: 2.0.0+2
  syncfusion_flutter_sliders: 20.2.44
  modal_bottom_sheet: 2.1.0
  dropdown_button2: 1.7.2
  recase: 4.0.0
  rate_my_app: 1.1.3
  collection: 1.16.0
  flutter_downloader: 1.8.4
  webview_flutter: 3.0.4

  jiffy: 5.0.0

  logger: ^1.1.0

  # in app purchase
  in_app_purchase: 3.0.7
  fl_chart: 0.55.1

  # firebase
  firebase_core: 1.20.1
  firebase_analytics: 9.3.1
  firebase_crashlytics: 2.8.7

  # ads
  google_mobile_ads: 2.0.1

  #hive
  hive: 2.2.3
  hive_flutter: 1.1.0

  json_annotation: 4.6.0

  assets_audio_player: 3.0.5
  audioplayers: 1.0.1

  file_picker: 5.2.0+1
  wakelock: 0.6.2

  flutter_easyloading: 3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
