name: l10n
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"
homepage: "https://kodingworks.io/"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: 2.7.0

flutter:

flutter_intl:
  enabled: true
  main_locale: en
