name: core
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"
homepage: "https://kodingworks.io/"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: ../dependencies
  l10n:
    path: ../l10n
  preferences:
    path: ../preferences
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  intl_utils: 2.7.0
  mockito: 5.3.0
  test_api: 0.4.12

flutter:

dependency_overrides:
  mockito: 5.3.0
  test_api: 0.4.12
